server: protect dataCache against concurrent access
As maps need to be protected against concurrent access we need to add a
mutex to protect those variables. Failing to do it so can cause the
program to crash with the following panic:

```
fatal error: concurrent map read and map write
```

Reported-by: Tam Mach <sayboras@yahoo.com>

Fixes: 79305bc39e09 ("fix: send updated link to client if verdict changed + domain types and cache refactor")
Signed-off-by: André Martins <andre@cilium.io>